services:

  app:
    build:
      context: .
    container_name: evaluation
    entrypoint: [ "dockerize", "-wait", "tcp://db:3306", "-timeout", "20s", "npm", "run", "start" ]
    networks:
      - app-network
    image: jeansouza007/evaluation
    volumes:
      - .:/usr/src/app
    tty: true
    environment:
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db-evaluation-test
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdatatest:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=evaluation_dev
      - POSTGRES_USER=jean
      - POSTGRES_ROOT_PASSWORD=docker123

  pgadmin:
    image: dpage/pgadmin4
    container_name: api-evaluation-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8000:80"
    depends_on:
      - db

networks:
  app-network:
    name: app-network
    driver: bridge
